### ISSUE TITLE
IntelliJ IDEA 2021.3.2 (Ultimate Edition)使用不了是个什么原因

### ISSUE THREAD

**Issue by Cheng-x-c** [starxg/mybatis-log-plugin-free#7]

**Comment by starxg** [comment]
可以详细说一下问题吗？

**Comment by Cheng-x-c** [comment]
已经解决了，是我自己配置的问题，需要在配置中开启mybatis日志。
```yaml
mybatis: 
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
```
